name: Hexo deployer # Actions 名字

on: # 触发条件
  push:
    branches:
      - hexo 

jobs:
  build: # job id
    name: Build and publish 
    runs-on: ubuntu-latest 

    steps:
      - uses: actions/checkout@v1 

      - name: Use Node.js 10.x 
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Setup Hexo env 
        run: |
          npm install hexo-cli -g
          npm install hexo-generator-sitemap
          cd themes\sagiri
          npm install
          cd ../../

      - name: Generate public files
        run: |
          hexo clean
          hexo g  

      - name: Deploy # 发布
        env:
        GH_REF: github.com/1574242600/1574242600.github.io.git
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name "1574242600"
          git config --global user.email "1574242600@qq.com"
          git clone https://${GH_REF} .deploy_git
          cd .deploy_git
          git checkout master
          cd ../
          mv .deploy_git/.git/ ./public/
          cd ./public/
          git add *
          git commit -m "CI built at `date +"%Y-%m-%d %H:%M:%S"`"
          git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
